name: terraform ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.0
          
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Vaildate
        run: |
          set -e

          for dir in \
            bootstrap \
            environments/dev/foundation \
            environments/dev/runtime \
            environments/prod/foundation \
            environments/prod/runtime
          do
            echo "validation for $dir"
            terraform -chdir="$dir" init -backend=false
            terraform -chdir="$dir" validate
          done